# Generated by Django 4.2.27 on 2025-12-12 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Місцезнаходження')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Соціальні мережі')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='action_logs.blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Ідентифікатор')),
                ('action_type', models.CharField(choices=[('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('view', 'Перегляд'), ('login', 'Вхід'), ('logout', 'Вихід'), ('download', 'Завантаження'), ('upload', 'Завантаження'), ('share', 'Поділитися'), ('other', 'Інша дія')], max_length=20, verbose_name='Тип дії')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="ID об'єкта")),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип вмісту')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог дії',
                'verbose_name_plural': 'Логи дій',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='action_logs_timesta_69b004_idx'), models.Index(fields=['action_type'], name='action_logs_action__de729f_idx'), models.Index(fields=['user'], name='action_logs_user_id_1dbdd3_idx'), models.Index(fields=['content_type', 'object_id'], name='action_logs_content_039c98_idx'), models.Index(fields=['ip_address'], name='action_logs_ip_addr_4dfdc7_idx')],
            },
        ),
    ]
